export interface Template {
  id: string;
  name: string;
  url: string;
  category: string;
}

export interface Category {
  id: string;
  name: string;
  nameEn: string;
  icon: string;
}

export const categories: Category[] = [
  { id: 'sports', name: 'Spor', nameEn: 'Sports', icon: 'football-outline' },
  { id: 'health', name: 'Sağlık', nameEn: 'Health', icon: 'medical-outline' },
  { id: 'news', name: 'Haber', nameEn: 'News', icon: 'newspaper-outline' },
  { id: 'technology', name: 'Teknoloji', nameEn: 'Technology', icon: 'hardware-chip-outline' },
  { id: 'education', name: 'Eğitim', nameEn: 'Education', icon: 'school-outline' },
  { id: 'entertainment', name: 'Eğlence', nameEn: 'Entertainment', icon: 'film-outline' },
  { id: 'shopping', name: 'Alışveriş', nameEn: 'Shopping', icon: 'cart-outline' },
  { id: 'social', name: 'Sosyal Medya', nameEn: 'Social Media', icon: 'people-outline' },
  { id: 'finance', name: 'Finans', nameEn: 'Finance', icon: 'cash-outline' },
  { id: 'travel', name: 'Seyahat', nameEn: 'Travel', icon: 'airplane-outline' },
];

export const templates: Record<string, Template[]> = {
  sports: [
    { id: 'sports-1', name: 'Fanatik', url: 'https://www.fanatik.com.tr', category: 'sports' },
    { id: 'sports-2', name: 'Sporx', url: 'https://www.sporx.com', category: 'sports' },
    { id: 'sports-3', name: 'NTV Spor', url: 'https://www.ntvspor.net', category: 'sports' },
    { id: 'sports-4', name: 'Fotomaç', url: 'https://www.fotomac.com.tr', category: 'sports' },
    { id: 'sports-5', name: 'TRT Spor', url: 'https://www.trtspor.com.tr', category: 'sports' },
    { id: 'sports-6', name: 'BeIN Sports', url: 'https://www.beinsports.com.tr', category: 'sports' },
    { id: 'sports-7', name: 'Ajansspor', url: 'https://www.ajansspor.com', category: 'sports' },
    { id: 'sports-8', name: 'Spor Haberleri', url: 'https://www.sporhaberleri.com', category: 'sports' },
    { id: 'sports-9', name: '90min Türkiye', url: 'https://www.90min.com/tr', category: 'sports' },
    { id: 'sports-10', name: 'Hürriyet Spor', url: 'https://www.hurriyet.com.tr/spor', category: 'sports' },
    { id: 'sports-11', name: 'Milliyet Spor', url: 'https://www.milliyet.com.tr/spor', category: 'sports' },
    { id: 'sports-12', name: 'Sabah Spor', url: 'https://www.sabah.com.tr/spor', category: 'sports' },
    { id: 'sports-13', name: 'Sözcü Spor', url: 'https://www.sozcu.com.tr/kategori/spor', category: 'sports' },
    { id: 'sports-14', name: 'CNN Türk Spor', url: 'https://www.cnnturk.com/spor', category: 'sports' },
    { id: 'sports-15', name: 'A Spor', url: 'https://www.aspor.com.tr', category: 'sports' },
    { id: 'sports-16', name: 'Spor Toto', url: 'https://www.spor-toto.com.tr', category: 'sports' },
    { id: 'sports-17', name: 'TFF', url: 'https://www.tff.org', category: 'sports' },
    { id: 'sports-18', name: 'Basketbol Haberleri', url: 'https://www.basketbolhaberleri.com', category: 'sports' },
    { id: 'sports-19', name: 'Voleybol Plus', url: 'https://www.voleybolplus.com', category: 'sports' },
    { id: 'sports-20', name: 'Spor İzle', url: 'https://www.sporizle.com', category: 'sports' },
  ],
  health: [
    { id: 'health-1', name: 'Sağlık Bakanlığı', url: 'https://www.saglik.gov.tr', category: 'health' },
    { id: 'health-2', name: 'Hürriyet Sağlık', url: 'https://www.hurriyet.com.tr/saglik', category: 'health' },
    { id: 'health-3', name: 'Milliyet Sağlık', url: 'https://www.milliyet.com.tr/saglik', category: 'health' },
    { id: 'health-4', name: 'NTV Sağlık', url: 'https://www.ntv.com.tr/saglik', category: 'health' },
    { id: 'health-5', name: 'CNN Türk Sağlık', url: 'https://www.cnnturk.com/saglik', category: 'health' },
    { id: 'health-6', name: 'Sabah Sağlık', url: 'https://www.sabah.com.tr/saglik', category: 'health' },
    { id: 'health-7', name: 'Sözcü Sağlık', url: 'https://www.sozcu.com.tr/kategori/saglik', category: 'health' },
    { id: 'health-8', name: 'Cumhuriyet Sağlık', url: 'https://www.cumhuriyet.com.tr/saglik', category: 'health' },
    { id: 'health-9', name: 'TRT Sağlık', url: 'https://www.trthaber.com/saglik', category: 'health' },
    { id: 'health-10', name: 'Memorial Sağlık', url: 'https://www.memorial.com.tr', category: 'health' },
    { id: 'health-11', name: 'Acıbadem Sağlık', url: 'https://www.acibadem.com.tr', category: 'health' },
    { id: 'health-12', name: 'Liv Hospital', url: 'https://www.livhospital.com', category: 'health' },
    { id: 'health-13', name: 'Anadolu Sağlık', url: 'https://www.anadolusaglik.org', category: 'health' },
    { id: 'health-14', name: 'Medipol Sağlık', url: 'https://www.medipol.com.tr', category: 'health' },
    { id: 'health-15', name: 'Florence Nightingale', url: 'https://www.florence.com.tr', category: 'health' },
    { id: 'health-16', name: 'Medical Park', url: 'https://www.medicalpark.com.tr', category: 'health' },
    { id: 'health-17', name: 'Hisar Intercontinental', url: 'https://www.hisarhospital.com', category: 'health' },
    { id: 'health-18', name: 'Koç Üniversitesi Hastanesi', url: 'https://www.kuh.ku.edu.tr', category: 'health' },
    { id: 'health-19', name: 'Sağlık Bilimleri Üniversitesi', url: 'https://www.sbu.edu.tr', category: 'health' },
    { id: 'health-20', name: 'Türk Tabipleri Birliği', url: 'https://www.ttb.org.tr', category: 'health' },
  ],
  news: [
    { id: 'news-1', name: 'Hürriyet', url: 'https://www.hurriyet.com.tr', category: 'news' },
    { id: 'news-2', name: 'Milliyet', url: 'https://www.milliyet.com.tr', category: 'news' },
    { id: 'news-3', name: 'Sabah', url: 'https://www.sabah.com.tr', category: 'news' },
    { id: 'news-4', name: 'Sözcü', url: 'https://www.sozcu.com.tr', category: 'news' },
    { id: 'news-5', name: 'Cumhuriyet', url: 'https://www.cumhuriyet.com.tr', category: 'news' },
    { id: 'news-6', name: 'NTV', url: 'https://www.ntv.com.tr', category: 'news' },
    { id: 'news-7', name: 'CNN Türk', url: 'https://www.cnnturk.com', category: 'news' },
    { id: 'news-8', name: 'TRT Haber', url: 'https://www.trthaber.com', category: 'news' },
    { id: 'news-9', name: 'Anadolu Ajansı', url: 'https://www.aa.com.tr', category: 'news' },
    { id: 'news-10', name: 'Habertürk', url: 'https://www.haberturk.com', category: 'news' },
    { id: 'news-11', name: 'A Haber', url: 'https://www.ahaber.com.tr', category: 'news' },
    { id: 'news-12', name: 'Star', url: 'https://www.star.com.tr', category: 'news' },
    { id: 'news-13', name: 'Yeni Şafak', url: 'https://www.yenisafak.com', category: 'news' },
    { id: 'news-14', name: 'Takvim', url: 'https://www.takvim.com.tr', category: 'news' },
    { id: 'news-15', name: 'Vatan', url: 'https://www.gazetevatan.com', category: 'news' },
    { id: 'news-16', name: 'Posta', url: 'https://www.posta.com.tr', category: 'news' },
    { id: 'news-17', name: 'Akşam', url: 'https://www.aksam.com.tr', category: 'news' },
    { id: 'news-18', name: 'Yeni Akit', url: 'https://www.yeniakit.com.tr', category: 'news' },
    { id: 'news-19', name: 'BirGün', url: 'https://www.birgun.net', category: 'news' },
    { id: 'news-20', name: 'Evrensel', url: 'https://www.evrensel.net', category: 'news' },
  ],
  technology: [
    { id: 'tech-1', name: 'ShiftDelete.Net', url: 'https://www.shiftdelete.net', category: 'technology' },
    { id: 'tech-2', name: 'Webtekno', url: 'https://www.webtekno.com', category: 'technology' },
    { id: 'tech-3', name: 'Donanım Haber', url: 'https://www.donanimhaber.com', category: 'technology' },
    { id: 'tech-4', name: 'Chip Online', url: 'https://www.chip.com.tr', category: 'technology' },
    { id: 'tech-5', name: 'Teknoloji Haberleri', url: 'https://www.teknoloji-haberleri.com', category: 'technology' },
    { id: 'tech-6', name: 'Teknolojioku', url: 'https://www.teknolojioku.com', category: 'technology' },
    { id: 'tech-7', name: 'Teknoloji Delisi', url: 'https://www.teknolojidelisi.com', category: 'technology' },
    { id: 'tech-8', name: 'Log.com.tr', url: 'https://www.log.com.tr', category: 'technology' },
    { id: 'tech-9', name: 'Teknoloji Haber', url: 'https://www.teknolojihaber.com', category: 'technology' },
    { id: 'tech-10', name: 'Teknoloji Blog', url: 'https://www.teknolojiblog.com', category: 'technology' },
    { id: 'tech-11', name: 'Hürriyet Teknoloji', url: 'https://www.hurriyet.com.tr/teknoloji', category: 'technology' },
    { id: 'tech-12', name: 'Milliyet Teknoloji', url: 'https://www.milliyet.com.tr/teknoloji', category: 'technology' },
    { id: 'tech-13', name: 'Sabah Teknoloji', url: 'https://www.sabah.com.tr/teknoloji', category: 'technology' },
    { id: 'tech-14', name: 'NTV Teknoloji', url: 'https://www.ntv.com.tr/teknoloji', category: 'technology' },
    { id: 'tech-15', name: 'CNN Türk Teknoloji', url: 'https://www.cnnturk.com/teknoloji', category: 'technology' },
    { id: 'tech-16', name: 'TRT Teknoloji', url: 'https://www.trthaber.com/teknoloji', category: 'technology' },
    { id: 'tech-17', name: 'Teknoloji Zamanı', url: 'https://www.teknolojizamani.com', category: 'technology' },
    { id: 'tech-18', name: 'Bilim ve Teknik', url: 'https://www.bilimteknik.tubitak.gov.tr', category: 'technology' },
    { id: 'tech-19', name: 'Teknoloji Dünyası', url: 'https://www.teknolojidunyasi.com', category: 'technology' },
    { id: 'tech-20', name: 'Teknoloji Rehberi', url: 'https://www.teknolojirehberi.com', category: 'technology' },
  ],
  education: [
    { id: 'edu-1', name: 'MEB', url: 'https://www.meb.gov.tr', category: 'education' },
    { id: 'edu-2', name: 'EBA', url: 'https://www.eba.gov.tr', category: 'education' },
    { id: 'edu-3', name: 'ÖSYM', url: 'https://www.osym.gov.tr', category: 'education' },
    { id: 'edu-4', name: 'YÖK', url: 'https://www.yok.gov.tr', category: 'education' },
    { id: 'edu-5', name: 'TÜBİTAK', url: 'https://www.tubitak.gov.tr', category: 'education' },
    { id: 'edu-6', name: 'TED', url: 'https://www.ted.org.tr', category: 'education' },
    { id: 'edu-7', name: 'Boğaziçi Üniversitesi', url: 'https://www.boun.edu.tr', category: 'education' },
    { id: 'edu-8', name: 'İTÜ', url: 'https://www.itu.edu.tr', category: 'education' },
    { id: 'edu-9', name: 'ODTÜ', url: 'https://www.metu.edu.tr', category: 'education' },
    { id: 'edu-10', name: 'Koç Üniversitesi', url: 'https://www.ku.edu.tr', category: 'education' },
    { id: 'edu-11', name: 'Sabancı Üniversitesi', url: 'https://www.sabanciuniv.edu', category: 'education' },
    { id: 'edu-12', name: 'Bilkent Üniversitesi', url: 'https://www.bilkent.edu.tr', category: 'education' },
    { id: 'edu-13', name: 'Ankara Üniversitesi', url: 'https://www.ankara.edu.tr', category: 'education' },
    { id: 'edu-14', name: 'İstanbul Üniversitesi', url: 'https://www.istanbul.edu.tr', category: 'education' },
    { id: 'edu-15', name: 'Hacettepe Üniversitesi', url: 'https://www.hacettepe.edu.tr', category: 'education' },
    { id: 'edu-16', name: 'Gazi Üniversitesi', url: 'https://www.gazi.edu.tr', category: 'education' },
    { id: 'edu-17', name: 'Ege Üniversitesi', url: 'https://www.ege.edu.tr', category: 'education' },
    { id: 'edu-18', name: 'Akademi Portal', url: 'https://www.akademiportal.com', category: 'education' },
    { id: 'edu-19', name: 'Eğitim Bilişim Ağı', url: 'https://www.eba.gov.tr', category: 'education' },
    { id: 'edu-20', name: 'Khan Academy Türkçe', url: 'https://tr.khanacademy.org', category: 'education' },
  ],
  entertainment: [
    { id: 'ent-1', name: 'BluTV', url: 'https://www.blutv.com', category: 'entertainment' },
    { id: 'ent-2', name: 'PuhuTV', url: 'https://www.puhutv.com', category: 'entertainment' },
    { id: 'ent-3', name: 'Exxen', url: 'https://www.exxen.com', category: 'entertainment' },
    { id: 'ent-4', name: 'TRT İzle', url: 'https://www.trtizle.com', category: 'entertainment' },
    { id: 'ent-5', name: 'YouTube Türkiye', url: 'https://www.youtube.com', category: 'entertainment' },
    { id: 'ent-6', name: 'Netflix Türkiye', url: 'https://www.netflix.com/tr', category: 'entertainment' },
    { id: 'ent-7', name: 'Spotify Türkiye', url: 'https://open.spotify.com', category: 'entertainment' },
    { id: 'ent-8', name: 'Beyazperde', url: 'https://www.beyazperde.com', category: 'entertainment' },
    { id: 'ent-9', name: 'Sinema.com', url: 'https://www.sinema.com', category: 'entertainment' },
    { id: 'ent-10', name: 'Diziler.com', url: 'https://www.diziler.com', category: 'entertainment' },
    { id: 'ent-11', name: 'SinemaTürk', url: 'https://www.sinematurk.com', category: 'entertainment' },
    { id: 'ent-12', name: 'Film.com.tr', url: 'https://www.film.com.tr', category: 'entertainment' },
    { id: 'ent-13', name: 'DiziBox', url: 'https://www.dizibox.com', category: 'entertainment' },
    { id: 'ent-14', name: 'Dizimag', url: 'https://www.dizimag.com', category: 'entertainment' },
    { id: 'ent-15', name: 'Mynet Dizi', url: 'https://dizi.mynet.com', category: 'entertainment' },
    { id: 'ent-16', name: 'Hürriyet Kelebek', url: 'https://www.hurriyet.com.tr/kelebek', category: 'entertainment' },
    { id: 'ent-17', name: 'Milliyet Cadde', url: 'https://www.milliyet.com.tr/cadde', category: 'entertainment' },
    { id: 'ent-18', name: 'Sabah Magazin', url: 'https://www.sabah.com.tr/magazin', category: 'entertainment' },
    { id: 'ent-19', name: 'NTV Magazin', url: 'https://www.ntv.com.tr/magazin', category: 'entertainment' },
    { id: 'ent-20', name: 'CNN Türk Magazin', url: 'https://www.cnnturk.com/magazin', category: 'entertainment' },
  ],
  shopping: [
    { id: 'shop-1', name: 'Trendyol', url: 'https://www.trendyol.com', category: 'shopping' },
    { id: 'shop-2', name: 'Hepsiburada', url: 'https://www.hepsiburada.com', category: 'shopping' },
    { id: 'shop-3', name: 'GittiGidiyor', url: 'https://www.gittigidiyor.com', category: 'shopping' },
    { id: 'shop-4', name: 'N11', url: 'https://www.n11.com', category: 'shopping' },
    { id: 'shop-5', name: 'ÇiçekSepeti', url: 'https://www.ciceksepeti.com', category: 'shopping' },
    { id: 'shop-6', name: 'Morhipo', url: 'https://www.morhipo.com', category: 'shopping' },
    { id: 'shop-7', name: 'Modanisa', url: 'https://www.modanisa.com', category: 'shopping' },
    { id: 'shop-8', name: 'LC Waikiki', url: 'https://www.lcwaikiki.com', category: 'shopping' },
    { id: 'shop-9', name: 'Koton', url: 'https://www.koton.com', category: 'shopping' },
    { id: 'shop-10', name: 'Mango', url: 'https://shop.mango.com/tr', category: 'shopping' },
    { id: 'shop-11', name: 'DeFacto', url: 'https://www.defacto.com.tr', category: 'shopping' },
    { id: 'shop-12', name: 'Teknosa', url: 'https://www.teknosa.com', category: 'shopping' },
    { id: 'shop-13', name: 'MediaMarkt', url: 'https://www.mediamarkt.com.tr', category: 'shopping' },
    { id: 'shop-14', name: 'Vatan Bilgisayar', url: 'https://www.vatanbilgisayar.com', category: 'shopping' },
    { id: 'shop-15', name: 'Migros', url: 'https://www.migros.com.tr', category: 'shopping' },
    { id: 'shop-16', name: 'CarrefourSA', url: 'https://www.carrefoursa.com', category: 'shopping' },
    { id: 'shop-17', name: 'BİM', url: 'https://www.bim.com.tr', category: 'shopping' },
    { id: 'shop-18', name: 'A101', url: 'https://www.a101.com.tr', category: 'shopping' },
    { id: 'shop-19', name: 'Şok', url: 'https://www.sokmarket.com.tr', category: 'shopping' },
    { id: 'shop-20', name: 'Getir', url: 'https://getir.com', category: 'shopping' },
  ],
  social: [
    { id: 'social-1', name: 'Facebook', url: 'https://www.facebook.com', category: 'social' },
    { id: 'social-2', name: 'Twitter', url: 'https://twitter.com', category: 'social' },
    { id: 'social-3', name: 'Instagram', url: 'https://www.instagram.com', category: 'social' },
    { id: 'social-4', name: 'LinkedIn', url: 'https://www.linkedin.com', category: 'social' },
    { id: 'social-5', name: 'TikTok', url: 'https://www.tiktok.com', category: 'social' },
    { id: 'social-6', name: 'WhatsApp Web', url: 'https://web.whatsapp.com', category: 'social' },
    { id: 'social-7', name: 'Telegram', url: 'https://web.telegram.org', category: 'social' },
    { id: 'social-8', name: 'Ekşi Sözlük', url: 'https://eksisozluk.com', category: 'social' },
    { id: 'social-9', name: 'Onedio', url: 'https://onedio.com', category: 'social' },
    { id: 'social-10', name: 'Mynet', url: 'https://www.mynet.com', category: 'social' },
    { id: 'social-11', name: 'Sosyal Medya Haberleri', url: 'https://www.sosyalmedyahaberleri.com', category: 'social' },
    { id: 'social-12', name: 'Webrazzi', url: 'https://webrazzi.com', category: 'social' },
    { id: 'social-13', name: 'TechCrunch Türkiye', url: 'https://techcrunch.com', category: 'social' },
    { id: 'social-14', name: 'Medium Türkçe', url: 'https://medium.com', category: 'social' },
    { id: 'social-15', name: 'Reddit', url: 'https://www.reddit.com', category: 'social' },
    { id: 'social-16', name: 'Discord', url: 'https://discord.com', category: 'social' },
    { id: 'social-17', name: 'Zoom', url: 'https://zoom.us', category: 'social' },
    { id: 'social-18', name: 'Skype', url: 'https://www.skype.com', category: 'social' },
    { id: 'social-19', name: 'Pinterest', url: 'https://www.pinterest.com', category: 'social' },
    { id: 'social-20', name: 'YouTube Türkiye', url: 'https://www.youtube.com', category: 'social' },
  ],
  finance: [
    { id: 'finance-1', name: 'Borsa İstanbul', url: 'https://www.borsaistanbul.com', category: 'finance' },
    { id: 'finance-2', name: 'Kap.org.tr', url: 'https://www.kap.org.tr', category: 'finance' },
    { id: 'finance-3', name: 'Finans Gündem', url: 'https://www.finansgundem.com', category: 'finance' },
    { id: 'finance-4', name: 'Ekonomist', url: 'https://www.ekonomist.com.tr', category: 'finance' },
    { id: 'finance-5', name: 'Para', url: 'https://www.para.com.tr', category: 'finance' },
    { id: 'finance-6', name: 'Dünya', url: 'https://www.dunya.com', category: 'finance' },
    { id: 'finance-7', name: 'Hürriyet Ekonomi', url: 'https://www.hurriyet.com.tr/ekonomi', category: 'finance' },
    { id: 'finance-8', name: 'Milliyet Ekonomi', url: 'https://www.milliyet.com.tr/ekonomi', category: 'finance' },
    { id: 'finance-9', name: 'Sabah Ekonomi', url: 'https://www.sabah.com.tr/ekonomi', category: 'finance' },
    { id: 'finance-10', name: 'NTV Ekonomi', url: 'https://www.ntv.com.tr/ekonomi', category: 'finance' },
    { id: 'finance-11', name: 'CNN Türk Ekonomi', url: 'https://www.cnnturk.com/ekonomi', category: 'finance' },
    { id: 'finance-12', name: 'TRT Ekonomi', url: 'https://www.trthaber.com/ekonomi', category: 'finance' },
    { id: 'finance-13', name: 'TCMB', url: 'https://www.tcmb.gov.tr', category: 'finance' },
    { id: 'finance-14', name: 'Hazine ve Maliye Bakanlığı', url: 'https://www.hmb.gov.tr', category: 'finance' },
    { id: 'finance-15', name: 'SPK', url: 'https://www.spk.gov.tr', category: 'finance' },
    { id: 'finance-16', name: 'BDDK', url: 'https://www.bddk.org.tr', category: 'finance' },
    { id: 'finance-17', name: 'Investing.com Türkiye', url: 'https://tr.investing.com', category: 'finance' },
    { id: 'finance-18', name: 'TradingView', url: 'https://www.tradingview.com', category: 'finance' },
    { id: 'finance-19', name: 'Paribu', url: 'https://www.paribu.com', category: 'finance' },
    { id: 'finance-20', name: 'BTCTürk', url: 'https://www.btcturk.com', category: 'finance' },
  ],
  travel: [
    { id: 'travel-1', name: 'Booking.com Türkiye', url: 'https://www.booking.com', category: 'travel' },
    { id: 'travel-2', name: 'Trivago Türkiye', url: 'https://www.trivago.com.tr', category: 'travel' },
    { id: 'travel-3', name: 'TripAdvisor Türkiye', url: 'https://www.tripadvisor.com.tr', category: 'travel' },
    { id: 'travel-4', name: 'Airbnb Türkiye', url: 'https://www.airbnb.com.tr', category: 'travel' },
    { id: 'travel-5', name: 'Skyscanner Türkiye', url: 'https://www.skyscanner.com.tr', category: 'travel' },
    { id: 'travel-6', name: 'THY', url: 'https://www.turkishairlines.com', category: 'travel' },
    { id: 'travel-7', name: 'Pegasus', url: 'https://www.flypgs.com', category: 'travel' },
    { id: 'travel-8', name: 'AnadoluJet', url: 'https://www.anadolujet.com', category: 'travel' },
    { id: 'travel-9', name: 'SunExpress', url: 'https://www.sunexpress.com', category: 'travel' },
    { id: 'travel-10', name: 'TCDD', url: 'https://www.tcddtasimacilik.gov.tr', category: 'travel' },
    { id: 'travel-11', name: 'Kültür ve Turizm Bakanlığı', url: 'https://www.ktb.gov.tr', category: 'travel' },
    { id: 'travel-12', name: 'GoTürkiye', url: 'https://www.goturkiye.com', category: 'travel' },
    { id: 'travel-13', name: 'Türkiye Turizm', url: 'https://www.turkiyeturizm.com', category: 'travel' },
    { id: 'travel-14', name: 'Tatil Sepeti', url: 'https://www.tatilsepeti.com', category: 'travel' },
    { id: 'travel-15', name: 'Setur', url: 'https://www.setur.com.tr', category: 'travel' },
    { id: 'travel-16', name: 'Jolly Tur', url: 'https://www.jolly.com.tr', category: 'travel' },
    { id: 'travel-17', name: 'Uber Türkiye', url: 'https://www.uber.com/tr/tr', category: 'travel' },
    { id: 'travel-18', name: 'BiTaksi', url: 'https://www.bitaksi.com', category: 'travel' },
    { id: 'travel-19', name: 'Martı', url: 'https://www.marti.tech', category: 'travel' },
    { id: 'travel-20', name: 'Hop', url: 'https://www.hop.com.tr', category: 'travel' },
  ],
};

export function getTemplatesByCategory(categoryId: string): Template[] {
  return templates[categoryId] || [];
}

export function getCategoryById(categoryId: string): Category | undefined {
  return categories.find(cat => cat.id === categoryId);
}

